# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Install pre-commit itself:
#   $ pip install pre-commit
#     OR
#   $ brew install pre-commit
#
# Update all pre-commit hooks to latest version:
#   $ pre-commit autoupdate
#
# Install all default pre-commit hooks locally:
#   $ pre-commit install
#
# Apply a given pre-commit hook to all files:
#   $ pre-commit run --all-files <id>
#
# Apply all pre-commit hooks to all files:
#   $ pre-commit run --all-files
ci:
  autoupdate_schedule: monthly
  submodules: true
repos:
 - repo: https://github.com/google/keep-sorted
   rev: c71803fd297b5736f3bfab1cfd84424ca52e961a  # frozen: v0.7.1
   hooks:
     - id: keep-sorted
